### ISSUE TITLE
The TS80P has an etch that says 30W. Okay to use 12v/40W?

### ISSUE THREAD

**Issue by spikespaz** [Ralim/IronOS-dfu#13]
Will I destroy my iron if I increase the wattage with this firmware?

**Comment by Ralim** [comment]
I'm not sure what you mean by "increase the wattage"?

Wattage is a measure of power drawn. Given the constant resistance of the tip and the fixed voltage of 12V, the wattage is therefore fixed.


If you connect the iron to a 35,40,45,60,100W power adapter it doesn't matter; it will still only draw around 30W.

**Comment by spikespaz** [comment]
By increase I mean the limit in the firmware advanced settings. Also, sorry for posting to the wrong repository, was just on the wrong tab.

**Comment by Ralim** [comment]
All good, we all do it :)

So that limiter wont come into effect unless your running higher voltages to be able to reach those wattages.
If your running at 12V it wont do anything.

**Comment by spikespaz** [comment]
Then I suppose I may adjust my question: How likely am I to destroy my iron if I disable the wattage limit and increase to 15v?

**Comment by Ralim** [comment]
So wattage limit doesnt come into effect here.

Since what will kill your Iron is either a component not handling the 15V _or_ a component not handling the current.
You would be doing 3.3A ish; which is _probably_ ok. But I have not (1) checked component ratings (2) tried this.

If you wanted to do this; it would come down to if the components could handle it; the software doesnt have control over any of this.

**Comment by spikespaz** [comment]
What is the limit for then?

**Comment by Ralim** [comment]
The unit is rated for 12V. For 12V operation you want a 30W or higher rated power supply. For USB PD you can use a supply that is capable of higher voltages safely as the PD firmware will negotiate correctly and only select up to 12V.

**Comment by spikespaz** [comment]
I see, so it will never negotiate for 12v/3.33a if the limit is off or for example 40w? It will always pick from an available voltage and current, listed on the PSU?

PD is not variadic, is it?

**Comment by Ralim** [comment]
These two things are unrelated.

So when you power it up off a PD source; it will use the tip resistance and the max voltage (12V) to find the highest voltage it can use up to the max voltage (12V), and select the highest voltage where the adaptor can supply the required current.

The wattage limiter comes later, and just limits the max duty cycle of the tip control to limit the _average_ power.

>PD is not variadic, is it?
Not sure what you mean by this. If you mean adjustable/variable: Yes, if your adaptor supports PPS or AVO then it can be adjusted and firmware will also check those to see if they offer a better combination.

**Comment by spikespaz** [comment]
Thanks for all the answers!
