### ISSUE TITLE
Unbricking docs

### ISSUE THREAD

**Issue by Unb0rn** [Ralim/IronOS-dfu#9]
Hey! It would be nice to have some doc on hardware flashing of backed up BL.
Looks like my TS100 bricked after flashing `bootloader.dfu` v0.2
The device is not recognized anymore with some errors like:

> usb 1-1: Device not responding to setup address.

In runtime mode everything went okay and I've dumped the stock BL(3.48) as per your instructions.
Luckily I have Hydrabus so I hope I'll be able to recover) Are there any guides or pinouts to flash it back with OpenOCD or something?
Thanks!

**Comment by Ralim** [comment]
Uh interesting.
Coming with 3.48 would suggest you have one of the new GD32 based chips rather than STM32.
I have one of these units and tested it here without issues.

On the newer models they usually connect the SWD pins to the usb data lines as well.
So you can wire up using a USB breakout the GND/5V and then breakout the D+/D- to SWDIO/SWCLK respectively.

You can then use your preferred means of writing your backup back.
If you can, taking a hex dump of the code on the device before flashing the backup back would be great.

**Comment by Unb0rn** [comment]
Just to be sure. Which tools can I use to dump the code? I am not sure if I can do it with standard `st-flash` tool but I want to be helpful on this issue =)

**Comment by Ralim** [comment]
st-flash can dump the stored code (`read`).
At a ballpark you probably want a command like `st-flash read readout.bin 0x8000000 64k`

**Comment by Unb0rn** [comment]
Well it was a really strange adventure) 
First, it looks like RDP bit was set so I was unable to read flash. Second, there was some really strange behavior-it was impossible to write anything to flash, although WP bits were all set to off.
After disabling RDP and first programming all WP to on and then back to off I was able to finally full-erase the chip.
After that I flashed the stock backed-up BL (btw, do you need it in your collection or maybe you already have one?), it booted fine, I re-installed IronOS-dfu the usual way, reflashed application through dfu-util and now voila, everything works as it should.
Sorry I was unable to dump anything for potential future debug...
Anyway, thank you!

**Comment by Ralim** [comment]
That is ok, I'm glad its working now.
Very interesting about RDP bits being set on.
I might add a warning about this.
Thank you for working this out 🤗 I hope this bootloader works well for you.

**Comment by jamesturton** [comment]
I also experienced a similar issue. Flashed runtime with stock bootloader, used dfu-util to load ironos bootloader, seemed to go ok, restarted the iron and nothing on the screen. I had to erase the option bits on the STM with by blackmagic probe before I could flash the bootloader over SWD.

Edit: I was using a 2 year old TS80P HW V1.1

**Comment by Ralim** [comment]
Oh that is interesting news to hear.
Any chance you knew what option bits had been set?

**Comment by jamesturton** [comment]
> Oh that is interesting news to hear.
> Any chance you knew what option bits had been set? 

No, I actually have another iron at work which is completely stock, so at some point I can try reading out how it looks

**Comment by jamesturton** [comment]
HW V1.2
DFU 3.50
APP 1.27

```
Open On-Chip Debugger
> stm32f1x options_read 0
option byte register = 0x3fffffe
write protection register = 0xffffffff
read protection: on
watchdog: software
stop mode: no reset generated upon entry
standby mode: no reset generated upon entry
user data = 0xffff
```

**Comment by doegox** [comment]
Hello, so trying to flash the bootloader from runtime DFU bricked my TS80P too.

Previous HW version but same option bits as above.
Everything was already said elsewhere but here is a little recap if someone else is seeking for all steps.

HW V1.1
DFU 3.50

I used a USBC breakout to connect the TS80P to a St-link v2

|USB|St-link v2|
|-|-|
|  GND|GND|
| Vcc|5V|
| D+|SWDIO|
| D-|SWCLK|

```
$ st-info --probe
  flash:      0 (pagesize: 1024)
  sram:       20480
  chipid:     0x0410
  descr:      F1xx Medium-density
```
So flash is locked.
Reading option bytes
```
$ openocd -d0  -f /usr/share/openocd/scripts/interface/stlink.cfg -f /usr/share/openocd/scripts/target/stm32f1x.cfg 
$ telnet 127.0.0.1 4444
> init
> reset halt
> stm32f1x options_read 0
option byte register = 0x3fffffe
write protection register = 0xffffffff
read protection: on
watchdog: software
stop mode: no reset generated upon entry
standby mode: no reset generated upon entry
user data = 0xffff
```
Then unlocking the flash
```
> stm32f1x unlock 0
stm32x unlocked.
```
Then after power cycling
```
$ st-info --probe
  flash:      65536 (pagesize: 1024)
  sram:       20480
  chipid:     0x0410
  descr:      F1xx Medium-density
```
Now the flash is ready to be written.
```
$ st-flash --format ihex write iron_os-dfu/releases/0.2/TS80P/bootloader.hex
```
And finally, using the brand new bootloader
* Unplug, maintain button A and plug
* `dfu-util -D iron_os/releases/v2.20/TS80P_EN.dfu`
* Unplug and replug
Not forgetting to flash your favorite boot logo too ;)
